### ISSUE TITLE
add the resource session . It would be beneficial for newcomers.

### ISSUE THREAD

**Issue by omk-coder** [nishantattrey07/nishantattrey07.github.io#8]

**Comment by omk-coder** [comment]
add a resource session . it would be beneficial for newcomes

**Comment by darkknight20032001** [comment]
Can u please explain more about the issue. I want to work on this.

**Comment by nishantattrey07** [comment]
He is saying about adding a resource section where we can add links to the resources that are helpful or we have used/using while learning.

**Comment by nishantattrey07** [comment]
Add a resource section where you can refer to the resources you used/using while learning.
